#!/bin/bash

set -e

CONFIGFILE="${HOME}/.noipupdaterrc"

if [ -f $CONFIGFILE ]; then
    source $CONFIGFILE
elif [ -f "/etc/noipupdater.conf" ]; then
    echo "Sourcing /etc/noipupdater.conf"
    source /etc/noipupdater.conf
else
    echo "Please copy noipupdaterrc.sample to $CONFIGFILE or /etc/noipupdater.conf and fill it in."
    exit 999
fi
echo "got past sourcing config..."

LOGFILE="$LOGDIR/noipupdater.log"
STOREDIPFILE="$CACHEDIR/current_ip"
USERAGENT="Simple Bash No-IP Updater/0.5 tampakrap@gmail.com"

[ -d $LOGDIR ] || mkdir $LOGDIR
[ -e $LOGFILE ] || touch $LOGFILE
[ -d $CACHEDIR ] || mkdir $CACHEDIR
[ -e $STOREDIPFILE ] || touch $STOREDIPFILE
echo "got past directory creation"

if [ ! -z $SSID ]; then
    echo "checking ssid"
    CURRENTSSID=$(/usr/sbin/iw wlp3s0 link 2> /dev/null | grep SSID | cut -d' ' -f2)
    [ $CURRENTSSID != $SSID ] && exit 1
fi

echo "Got past current ssid"

if [ ! -z $ROUTERURL ]; then
    NEWIP=$(curl -s "http://$ROUTERUSER:$ROUTERPASSWORD@$ROUTERURL" | grep -m 1 $ROUTERIPSTRING | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
else
    NEWIP=$(curl -4 --silent http://ip.appspot.com)
fi
echo "NEWIP: $NEWIP"

STOREDIP=$(cat $STOREDIPFILE)

if [ "$NEWIP" != "$STOREDIP" ]; then
    RESULT=$(curl -k -s --user-agent "$USERAGENT" "https://$USERNAME:$PASSWORD@dynupdate.no-ip.com/nic/update?hostname=$HOST&myip=$NEWIP")
    echo $NEWIP > $STOREDIPFILE
    echo "[$(date +"%Y-%m-%d %H:%M:%S")] $RESULT" >> $LOGFILE
fi
