#!/bin/bash
# Extra bash custimizations. The real magic happens in /usr/local/etc/bashrc.d
# Copyright (C) 2015-2016 Dan Reidy <dubkat+github@gmail.com>
# http://github.com/dubkat/misc-linux-tools/usr-local-etc

declare -A ULE_VERSION
declare -r ULE_MODULES="base console environ functions setup colorize aliases"
ULE_VERSION['base']=16.06.04

if [ ! -z "${TERM}" ] && [ "$is" = "bash" ]; then
        if [ -d /usr/local/etc/bashrc.d ]; then
               	for sh in /usr/local/etc/bashrc.d/*.sh; do
                        if [ -r ${sh} ]; then
                                . ${sh};
                        fi
        	done
        fi
fi
