#!/bin/bash
# Extra bash custimizations. The real magic happens in /usr/local/etc/bashrc.d
# Copyright (C) 2015-2016 Dan Reidy <dubkat+github@gmail.com>
# http://github.com/dubkat/misc-linux-tools/usr-local-etc

declare -A ULE_VERSION;
ULE_VERSION['base']=16.06.8

if [ ! -z "$ULE_RUNTIME" ]; then
	# prevent source looping
	return
fi
export ULE_RUNTIME=1

if [ -z "$ULE_MODULES" ]; then
        declare -r ULE_MODULES="base start environ functions setup colorize aliases"
fi

declare -A ULE_SETTING;
ULE_SETTING['ETC_DIR']="%env_prefix%"
ULE_SETTING['BIN_DIR']="%bin_prefix%"
ULE_SETTING['SBIN_DIR']="%sbin_prefix%"


if [ ! -z "${TERM}" ] && [ "$is" = "bash" ]; then
        if [ -d ${ULE_SETTING['ETC_DIR']}/bashrc.d ]; then
               	for sh in ${ULE_SETTING['ETC_DIR']}/bashrc.d/*.sh; do
                        if [ -r ${sh} ]; then
                                . ${sh};
                        fi
        	done
        fi
fi

unset ULE_RUNTIME
