#!/bin/bash
# Extra bash custimizations. The real magic happens in /usr/local/etc/bashrc.d
# Copyright (C) 2015-2016 Dan Reidy <dubkat+github@gmail.com>
# http://github.com/dubkat/misc-linux-tools/usr-local-etc

if [ "x${PS1}" != "x" ] && [ "$is" = "bash" ]; then
        if [ -d /usr/local/etc/bashrc.d ]; then
        	for sh in /usr/local/etc/bashrc.d/*.sh; do
        		test -r ${sh} && . ${sh}
        	done
        fi
fi

#umask 027
